# 09. Advanced NumPy Operations | العمليات المتقدمة في NumPy

## 📚 Learning Objectives

By completing this notebook, you will:
- Master advanced NumPy operations (broadcasting, vectorization)
- Understand matrix operations and linear algebra with NumPy
- Apply advanced indexing and slicing techniques
- Optimize numerical computations using NumPy

## 🔗 Prerequisites

- ✅ Example 2: pandas & NumPy Basics
- ✅ Understanding of basic NumPy arrays

---

## Official Structure Reference

This notebook supports **Course 05, Unit 1** requirements from `DETAILED_UNIT_DESCRIPTIONS.md`.

---


# 09. Advanced NumPy Operations | العمليات المتقدمة في NumPy

**All concepts are explained in the code comments below - you can learn everything from this notebook alone!**

---

## 🔗 Building on Example 2 | البناء على المثال 2

**Remember from Example 2?**
- We learned basic NumPy arrays and operations
- We saw how NumPy is faster than Python lists
- But we only scratched the surface!

**This notebook goes deeper!**
- We'll learn **broadcasting** - powerful array operations
- We'll learn **vectorization** - fast operations on entire arrays
- We'll learn **matrix operations** - linear algebra with NumPy
- We'll learn **advanced indexing** - powerful data selection

**This unlocks the full power of NumPy!**

---

## Learning Objectives | أهداف التعلم
1. Understand broadcasting and vectorization
2. Perform matrix operations (multiplication, transpose, inverse)
3. Use advanced indexing (boolean, fancy indexing)
4. Optimize computations using NumPy best practices

In [1]:
# Step 1: Import NumPy
import numpy as np
import time

print("✅ NumPy imported successfully!")
print("\n📚 This notebook covers:")
print("   - Broadcasting (automatic dimension expansion)")
print("   - Vectorization (fast array operations)")
print("   - Matrix operations (linear algebra)")
print("   - Advanced indexing (powerful selection)")

✅ NumPy imported successfully!

📚 This notebook covers:
   - Broadcasting (automatic dimension expansion)
   - Vectorization (fast array operations)
   - Matrix operations (linear algebra)
   - Advanced indexing (powerful selection)


In [2]:
# Step 2: Broadcasting - Automatic Dimension Expansion
print("=" * 70)
print("1. Broadcasting | البث التلقائي")
print("=" * 70)

# Example: Add scalar to array (broadcasting)
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to each element
print(f"Array: {arr}")
print(f"Array + 10: {result}")
print("\n💡 Broadcasting automatically expands dimensions!")

# Example: Add 1D array to 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
result_2d = arr_2d + arr_1d  # Broadcasting: adds to each row
print(f"\n2D Array:\n{arr_2d}")
print(f"1D Array: {arr_1d}")
print(f"Result (broadcasted):\n{result_2d}")

1. Broadcasting | البث التلقائي
Array: [1 2 3 4 5]
Array + 10: [11 12 13 14 15]

💡 Broadcasting automatically expands dimensions!

2D Array:
[[1 2 3]
 [4 5 6]]
1D Array: [10 20 30]
Result (broadcasted):
[[11 22 33]
 [14 25 36]]


In [3]:
# Step 3: Matrix Operations
print("\n" + "=" * 70)
print("2. Matrix Operations | عمليات المصفوفات")
print("=" * 70)

# Create matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"Matrix A:\n{A}")
print(f"\nMatrix B:\n{B}")

# Matrix multiplication
C = np.dot(A, B)  # or A @ B
print(f"\nA @ B (matrix multiplication):\n{C}")

# Transpose
A_T = A.T
print(f"\nA transpose:\n{A_T}")

# Determinant
det_A = np.linalg.det(A)
print(f"\nDeterminant of A: {det_A:.2f}")


2. Matrix Operations | عمليات المصفوفات
Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A @ B (matrix multiplication):
[[19 22]
 [43 50]]

A transpose:
[[1 3]
 [2 4]]

Determinant of A: -2.00


In [4]:
# Step 4: Advanced Indexing
print("\n" + "=" * 70)
print("3. Advanced Indexing | الفهرسة المتقدمة")
print("=" * 70)

# Boolean indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = arr > 5  # Boolean mask
filtered = arr[mask]  # Select elements where mask is True
print(f"Array: {arr}")
print(f"Mask (arr > 5): {mask}")
print(f"Filtered (arr[mask]): {filtered}")

# Fancy indexing
indices = [0, 2, 4, 6]
selected = arr[indices]
print(f"\nFancy indexing (indices {indices}): {selected}")


3. Advanced Indexing | الفهرسة المتقدمة
Array: [ 1  2  3  4  5  6  7  8  9 10]
Mask (arr > 5): [False False False False False  True  True  True  True  True]
Filtered (arr[mask]): [ 6  7  8  9 10]

Fancy indexing (indices [0, 2, 4, 6]): [1 3 5 7]


In [5]:
# Step 5: Performance Comparison
print("\n" + "=" * 70)
print("4. Performance: Vectorization vs Loops | الأداء")
print("=" * 70)

large_arr = np.random.rand(1_000_000)

# Vectorized operation (fast)
start = time.time()
result_vectorized = large_arr * 2  # Vectorized
time_vectorized = time.time() - start

# Loop operation (slow)
start = time.time()
result_loop = np.array([x * 2 for x in large_arr])
time_loop = time.time() - start

print(f"Vectorized: {time_vectorized:.4f} seconds")
print(f"Loop: {time_loop:.4f} seconds")
print(f"\nSpeedup: {time_loop/time_vectorized:.1f}x faster with vectorization!")
print("\n💡 Always use vectorized operations when possible!")


4. Performance: Vectorization vs Loops | الأداء
Vectorized: 0.0006 seconds
Loop: 0.0508 seconds

Speedup: 90.8x faster with vectorization!

💡 Always use vectorized operations when possible!
