# Computing Determinants and Inverse Matrices

## 📚 Learning Objectives

By completing this notebook, you will:
- Compute determinants and inverse matrices computationally using Python/NumPy
- Understand the relationship between determinants and matrix invertibility
- Apply determinants and inverses to ML problems
- Handle singular and near-singular matrices

## 🔗 Prerequisites

- ✅ Understanding of matrix operations
- ✅ Python and NumPy knowledge

---

## Official Structure Reference

This notebook covers practical activities from **Course 03, Unit 1**:
- Computing determinants and inverse matrices computationally
- **Source:** `DETAILED_UNIT_DESCRIPTIONS.md` - Unit 1 Practical Content

---

## Introduction

**Determinants** measure matrix invertibility, and **inverse matrices** are used in solving linear systems and optimization problems in machine learning.


In [1]:
import numpy as np
import matplotlib.pyplot as plt

print("✅ Libraries imported!")
print("\nComputing Determinants and Inverse Matrices")
print("=" * 60)


✅ Libraries imported!

Computing Determinants and Inverse Matrices


## Part 1: Computing Determinants


In [2]:
print("=" * 60)
print("Part 1: Computing Determinants")
print("=" * 60)

# Determinant of 2x2 matrix: det([[a,b],[c,d]]) = ad - bc
def determinant_2x2(matrix):
    """Compute determinant of 2x2 matrix"""
    return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]

# Determinant of 3x3 matrix using cofactor expansion
def determinant_3x3(matrix):
    """Compute determinant of 3x3 matrix"""
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]
    return a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

# Example matrices
A_2x2 = np.array([[2, 1],
                  [1, -1]])
A_3x3 = np.array([[2, 1, -1],
                  [-3, -1, 2],
                  [-2, 1, 2]])

print("\n2x2 Matrix:")
print(A_2x2)
det_2x2_manual = determinant_2x2(A_2x2)
det_2x2_numpy = np.linalg.det(A_2x2)
print(f"Determinant (manual): {det_2x2_manual:.2f}")
print(f"Determinant (NumPy): {det_2x2_numpy:.2f}")

print("\n3x3 Matrix:")
print(A_3x3)
det_3x3_manual = determinant_3x3(A_3x3)
det_3x3_numpy = np.linalg.det(A_3x3)
print(f"Determinant (manual): {det_3x3_manual:.2f}")
print(f"Determinant (NumPy): {det_3x3_numpy:.2f}")

# Properties of determinants
print("\n" + "-" * 60)
print("Properties of Determinants:")
print("-" * 60)
print("1. det(A^T) = det(A)")
print(f"   det(A) = {np.linalg.det(A_2x2):.2f}, det(A^T) = {np.linalg.det(A_2x2.T):.2f}")

print("\n2. det(AB) = det(A) * det(B)")
B_2x2 = np.array([[1, 2], [3, 4]])
print(f"   det(A) * det(B) = {np.linalg.det(A_2x2) * np.linalg.det(B_2x2):.2f}")
print(f"   det(AB) = {np.linalg.det(A_2x2 @ B_2x2):.2f}")

print("\n3. If det(A) = 0, A is singular (not invertible)")
singular = np.array([[1, 2], [2, 4]])  # Second row is 2x first row
print(f"   Singular matrix det = {np.linalg.det(singular):.2f}")

print("\n✅ Determinant computation implemented!")


Part 1: Computing Determinants

2x2 Matrix:
[[ 2  1]
 [ 1 -1]]
Determinant (manual): -3.00
Determinant (NumPy): -3.00

3x3 Matrix:
[[ 2  1 -1]
 [-3 -1  2]
 [-2  1  2]]
Determinant (manual): -1.00
Determinant (NumPy): -1.00

------------------------------------------------------------
Properties of Determinants:
------------------------------------------------------------
1. det(A^T) = det(A)
   det(A) = -3.00, det(A^T) = -3.00

2. det(AB) = det(A) * det(B)
   det(A) * det(B) = 6.00
   det(AB) = 6.00

3. If det(A) = 0, A is singular (not invertible)
   Singular matrix det = 0.00

✅ Determinant computation implemented!


## Part 2: Computing Inverse Matrices


In [3]:
print("\n" + "=" * 60)
print("Part 2: Computing Inverse Matrices")
print("=" * 60)

# For 2x2: A^(-1) = (1/det(A)) * [[d, -b], [-c, a]] where A = [[a, b], [c, d]]
def inverse_2x2(matrix):
    """Compute inverse of 2x2 matrix"""
    det = determinant_2x2(matrix)
    if abs(det) < 1e-10:
        raise ValueError("Matrix is singular (determinant is 0)")
    
    a, b = matrix[0]
    c, d = matrix[1]
    inv = (1/det) * np.array([[d, -b], [-c, a]])
    return inv

# Example
A = np.array([[2, 1],
              [1, -1]])

print(f"Matrix A:\n{A}")
print(f"\nDeterminant: {np.linalg.det(A):.2f}")

# Manual computation
A_inv_manual = inverse_2x2(A)
print(f"\nInverse (manual):\n{A_inv_manual}")

# NumPy computation
A_inv_numpy = np.linalg.inv(A)
print(f"\nInverse (NumPy):\n{A_inv_numpy}")

# Verify: A * A^(-1) = I
I_check = A @ A_inv_numpy
print(f"\nVerification (A * A^(-1) should be identity):\n{I_check}")
print(f"\nIdentity matrix:\n{np.eye(2)}")

# Using NumPy's pinv for near-singular matrices
print("\n" + "-" * 60)
print("Handling Near-Singular Matrices:")
print("-" * 60)
nearly_singular = np.array([[1, 2.0001],
                            [2, 4]])
print(f"Nearly singular matrix:\n{nearly_singular}")
print(f"Determinant: {np.linalg.det(nearly_singular):.6f}")

try:
    inv_regular = np.linalg.inv(nearly_singular)
    print(f"Inverse (regular):\n{inv_regular}")
except np.linalg.LinAlgError:
    print("Regular inverse fails (singular matrix)")

# Use pseudo-inverse for stability
inv_pseudo = np.linalg.pinv(nearly_singular)
print(f"Pseudo-inverse (stable):\n{inv_pseudo}")

print("\n✅ Inverse matrix computation implemented!")



Part 2: Computing Inverse Matrices
Matrix A:
[[ 2  1]
 [ 1 -1]]

Determinant: -3.00

Inverse (manual):
[[ 0.33333333  0.33333333]
 [ 0.33333333 -0.66666667]]

Inverse (NumPy):
[[ 0.33333333  0.33333333]
 [ 0.33333333 -0.66666667]]

Verification (A * A^(-1) should be identity):
[[1.00000000e+00 0.00000000e+00]
 [5.55111512e-17 1.00000000e+00]]

Identity matrix:
[[1. 0.]
 [0. 1.]]

------------------------------------------------------------
Handling Near-Singular Matrices:
------------------------------------------------------------
Nearly singular matrix:
[[1.     2.0001]
 [2.     4.    ]]
Determinant: -0.000200
Inverse (regular):
[[-19999.99999996  10000.49999998]
 [  9999.99999998  -4999.99999999]]
Pseudo-inverse (stable):
[[-20000.00000014  10000.50000007]
 [ 10000.00000007  -5000.00000003]]

✅ Inverse matrix computation implemented!


## Part 3: Application to ML Problems


In [4]:
print("\n" + "=" * 60)
print("Part 3: Application to ML Problems")
print("=" * 60)

# Example: Linear regression using normal equations
# w = (X^T * X)^(-1) * X^T * y
print("\nLinear Regression Using Matrix Inversion:")
print("-" * 60)

# Sample data
X_data = np.array([1, 2, 3, 4, 5])
y_data = np.array([2, 4, 5, 4, 5])

# Design matrix
X = np.vstack([np.ones(len(X_data)), X_data]).T

# Normal equations: (X^T * X) * w = X^T * y
# w = (X^T * X)^(-1) * X^T * y
XTX = X.T @ X
XTy = X.T @ y_data

print(f"X^T * X:\n{XTX}")
print(f"\nDeterminant of (X^T * X): {np.linalg.det(XTX):.2f}")

# Check if invertible
if np.linalg.det(XTX) > 1e-10:
    XTX_inv = np.linalg.inv(XTX)
    w = XTX_inv @ XTy
    print(f"\nInverse of (X^T * X):\n{XTX_inv}")
    print(f"\nWeights: w0 = {w[0]:.2f}, w1 = {w[1]:.2f}")
    print(f"Model: y = {w[0]:.2f} + {w[1]:.2f}*x")
else:
    print("Matrix is singular, use pseudo-inverse")
    XTX_inv = np.linalg.pinv(XTX)
    w = XTX_inv @ XTy
    print(f"Weights: w0 = {w[0]:.2f}, w1 = {w[1]:.2f}")

# Compare with direct solve (more stable)
w_solve = np.linalg.solve(XTX, XTy)
print(f"\nUsing np.linalg.solve (more stable):")
print(f"Weights: w0 = {w_solve[0]:.2f}, w1 = {w_solve[1]:.2f}")

print("\n✅ ML application: Linear regression using matrix inversion!")



Part 3: Application to ML Problems

Linear Regression Using Matrix Inversion:
------------------------------------------------------------
X^T * X:
[[ 5. 15.]
 [15. 55.]]

Determinant of (X^T * X): 50.00

Inverse of (X^T * X):
[[ 1.1 -0.3]
 [-0.3  0.1]]

Weights: w0 = 2.20, w1 = 0.60
Model: y = 2.20 + 0.60*x

Using np.linalg.solve (more stable):
Weights: w0 = 2.20, w1 = 0.60

✅ ML application: Linear regression using matrix inversion!


## Summary

### Key Concepts:
1. **Determinant**: Scalar value indicating matrix invertibility
   - det(A) = 0 → matrix is singular (not invertible)
   - det(A) ≠ 0 → matrix is invertible

2. **Inverse Matrix**: A^(-1) such that A * A^(-1) = I
   - Used for solving linear systems
   - Computationally expensive (use solve() instead when possible)

3. **Pseudo-Inverse**: Used for singular or near-singular matrices
   - More numerically stable
   - Useful in ML for regularization

### Best Practices:
- Use `np.linalg.solve()` instead of computing inverse explicitly
- Check determinant before inversion (avoid singular matrices)
- Use pseudo-inverse (`pinv`) for near-singular matrices
- Verify A * A^(-1) = I after computation

### Applications:
- Linear regression (normal equations)
- Solving linear systems
- Optimization problems
- Neural network weight updates

**Reference:** Course 03, Unit 1: "Linear Algebra for Machine Learning" - Determinants and inverses practical content
